version: '3.8'
services:
    
    db:
        container_name: pg_container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${THRIFTY_USER}
            POSTGRES_PASSWORD: ${THRIFTY_PASSWORD}"
            POSTGRES_DB: ${THRIFTY_DB_NAME}
        ports:
            - "54320:5432"
        volumes:
            - $HOME/Documents/thrifty
            - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data:
